import { CardGrid, CardLink } from "@/components/docs/content/card-grid";
import type { PageMeta } from "@/lib/content/types";

export const meta: PageMeta = {
  eyebrow: "Customer portal",
  title: "Customer portal",
  lede: "Let your subscribers manage their own account. View, pause, resume, cancel, update payment method, no support ticket required.",
};

export default function CustomerPortalOverview() {
  return (
    <>
      <p>
        Every merchant on this platform gets a customer self-service portal
        customer management. Configure the portal in the Dashboard.
      </p>

      <h2 id="h-start">Where to go from here</h2>
      <CardGrid cols={2}>
        <CardLink
          href="/demo/portal"
          icon="▶️"
          title="Explore demo"
          description="A live, clickable walkthrough: view a plan, switch plans with real proration, pause, cancel, reactivate."
          external
        />
        <CardLink
          href="/merchants/customer-portal/no-code-setup"
          icon="🔘"
          title="Create a customer portal"
          description="Create a customer portal to enable your customers to manage their account  and subscription status."
        />
        <CardLink
          href="/merchants/customer-portal/api-setup"
          icon="💻"
          title="Set up the customer portal with the API"
          description="Generate portal links programmatically, listen for the webhooks that matter."
        />
        <CardLink
          href="/merchants/customer-portal/configure"
          icon="🎛️"
          title="Configure the customer portal"
          description="Which actions are on, which are off, and what a subscriber can edit."
        />
        <CardLink
          href="/merchants/customer-portal/deep-links-and-flows"
          icon="🔗"
          title="Deep links and flows"
          description="A signed, single-use link into one specific action. The same primitive our recovery messages already use."
        />
        <CardLink
          href="/merchants/customer-portal/cancellation-page"
          icon="✖️"
          title="Add a cancellation page"
          description="Collect a reason. Offer Pause or Downgrade first."
        />
      </CardGrid>

      <h2 id="h-features">What the portal actually does</h2>
      <table>
        <tr>
          <th>Capability</th>
          <th>Detail</th>
        </tr>
        <tr>
          <td>View subscription</td>
          <td>
            Current plan, price, next billing date, and payment history (FR-13).
          </td>
        </tr>
        <tr>
          <td>Pause / resume</td>
          <td>
            Stop and restart billing without cancelling, without re-onboarding
            (FR-14).
          </td>
        </tr>
        <tr>
          <td>Cancel</td>
          <td>
            On by default; optionally captures a reason and offers Pause or
            Downgrade first (FR-14).
          </td>
        </tr>
        <tr>
          <td>Update payment method</td>
          <td>
            Re-tokenised through Nomba Checkout, the portal never sees a raw
            card number (FR-15).
          </td>
        </tr>
        <tr>
          <td>Invoice history</td>
          <td>
            Read-only list of past invoices, sourced from the same{" "}
            <code className="inline">GET /invoices</code> a merchant sees.
          </td>
        </tr>
        <tr>
          <td>Deep links</td>
          <td>
            A scoped, signed, single-use link into exactly one of the above
            actions, generated by you or by our own recovery messages.
          </td>
        </tr>
      </table>
      <p>
        Every action a subscriber takes here writes to the same audit log and
        event store as a merchant-initiated change, see{" "}
        <a href="/concepts/event-store">The event store</a>.
      </p>

      <h2 id="h-limits">What the portal doesn&apos;t do</h2>
      <table>
        <tr>
          <th>Not supported</th>
          <th>Why</th>
        </tr>
        <tr>
          <td>Multi-currency, FX-aware billing</td>
          <td>
            Out of scope for this release; see{" "}
            <a href="/mission">The mission</a>.
          </td>
        </tr>
        <tr>
          <td>Tax ID collection</td>
          <td>No tax-compliance workflow (VAT, WHT) exists in this release.</td>
        </tr>
        <tr>
          <td>Editing your own registered email</td>
          <td>
            Security boundary. Changing the identity a login resolves to
            isn&apos;t a self-serve action; contact the merchant.
          </td>
        </tr>
        <tr>
          <td>Seat or quantity-based plan changes</td>
          <td>
            Plans are priced per interval, not per seat. There&apos;s no
            quantity field to update.
          </td>
        </tr>
        <tr>
          <td>Coupon-based retention offers</td>
          <td>
            No discount or coupon entity exists in the platform. The
            cancellation page offers Pause or Downgrade instead, see{" "}
            <a href="/merchants/customer-portal/cancellation-page">
              Add a cancellation page
            </a>
            .
          </td>
        </tr>
        <tr>
          <td>Custom branding or theming</td>
          <td>The portal is unbranded at v1, same look for every merchant.</td>
        </tr>
      </table>

      <h2 id="h-next">Next</h2>
      <CardGrid cols={2}>
        <CardLink
          href="/merchants/customer-portal/no-code-setup"
          icon="🔘"
          title="No-code setup"
          description="Nothing to activate. Here's what you configure instead."
        />
        <CardLink
          href="/subscribers/manage-your-subscription"
          icon="🙋"
          title="Manage your subscription"
          description="The same page, from the subscriber's side."
        />
      </CardGrid>
    </>
  );
}
