import { CardGrid, CardLink } from "@/components/docs/content/card-grid";
import type { PageMeta } from "@/lib/content/types";
import { Compass, MessageCircle } from "lucide-react";

export const meta: PageMeta = {
  eyebrow: "Channels",
  title: "Email",
  lede: "The baseline channel. Every recovery sequence sends one, whether or not WhatsApp or SMS also fire.",
};

export default function ChannelsEmail() {
  return (
    <>
      <p>
        Email is the one channel that fires on every recovery attempt, no exceptions. WhatsApp depends on a
        subscriber having WhatsApp; SMS depends on a phone number that accepts text; USSD depends on the subscriber
        dialling in themselves. Email just needs the address a subscriber signed up with, which every subscriber
        has, because it&apos;s how checkout confirmations and receipts already reach them.
      </p>

      <h2 id="h-what">What arrives by email</h2>
      <p>The same failed-charge notice as WhatsApp, formatted for a longer read and a written record.</p>
      <blockquote>
        Subject: Your Lumen Monthly payment didn&apos;t go through
        <br />
        Your card was charged ₦15,000 for Lumen Monthly and the payment failed. [Retry Now] [Pause Subscription]
        [Downgrade Plan]
      </blockquote>
      <p>
        Each action is a signed, single-use link rather than a button that needs an app to render, so the email
        works the same whether it&apos;s opened on a phone, a shared cybercafé desktop, or a work laptop. It&apos;s
        the same portal-link primitive covered in full in{" "}
        <a href="/merchants/customer-portal/deep-links-and-flows">Deep links and flows</a>, generated by our own
        recovery-orchestration component instead of by you.
      </p>

      <h2 id="h-role">Why it&apos;s the baseline, not a fallback</h2>
      <p>
        WhatsApp and SMS fall back to each other because a subscriber can only be reached on one of them at a time.
        Email isn&apos;t part of that either/or, it&apos;s sent in parallel on every recovery attempt, regardless of
        whether WhatsApp or SMS also succeed. That&apos;s deliberate: some merchants&apos; subscribers are more
        email-native than phone-native (a B2B SaaS customer expensing a subscription, for instance), and a written,
        addressable record of every failed charge and every recovery is useful even when a faster channel already
        resolved it.
      </p>

      <h2 id="h-scope">What email is, and isn&apos;t, used for</h2>
      <p>
        Like WhatsApp, this channel is scoped to dunning, not general product communication. Plan changes a
        merchant makes, receipts, and marketing don&apos;t run through this pipeline; the recovery-orchestration
        component only sends what a subscriber needs to fix a specific failed charge.
      </p>

      <h2 id="h-next">Next</h2>
      <CardGrid cols={2}>
        <CardLink
          href="/channels/whatsapp"
          icon={MessageCircle}
          title="WhatsApp"
          description="The richest channel, when a phone's on file."
        />
        <CardLink
          href="/concepts/recovery-orchestration"
          icon={Compass}
          title="Recovery orchestration"
          description="How email fits alongside the other three channels."
        />
      </CardGrid>
    </>
  );
}
